/**
 * Migration writer: serialize operations into a numbered migration file.
 *
 * Deviation from design 10.2's class-style sketch: files default-export a plain
 * object whose `operations` is a factory receiving the `ops` namespace. That
 * keeps generated files import-free — they run from any directory layout
 * without resolving the "dorm" package — while staying plain readable code.
 */
import { writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { Operation } from "./operations.ts";

export const MIGRATION_FILE_RE = /^(\d{4})_([\w-]+)\.(ts|js|mjs)$/;

/** Existing migration files in order ([number, filename]). */
export function listMigrationFiles(
  dir: string,
): Array<{ number: number; name: string; file: string }> {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .map((f) => {
      const m = MIGRATION_FILE_RE.exec(f);
      return m ? { number: Number(m[1]), name: `${m[1]}_${m[2]}`, file: join(dir, f) } : null;
    })
    .filter((x): x is { number: number; name: string; file: string } => x !== null)
    .sort((a, b) => a.number - b.number);
}

export function nextMigrationName(
  dir: string,
  suggested?: string,
): { number: number; name: string } {
  const existing = listMigrationFiles(dir);
  const number = (existing[existing.length - 1]?.number ?? 0) + 1;
  const slug = suggested ?? (number === 1 ? "initial" : "auto");
  return { number, name: `${String(number).padStart(4, "0")}_${slug}` };
}

export function renderMigration(
  operations: Operation[],
  dependencies: string[],
  replaces?: string[],
): string {
  const opsCode = operations.map((op) => `    ${op.toCode()},`).join("\n");
  const replacesLine =
    replaces && replaces.length > 0 ? `\n  replaces: ${JSON.stringify(replaces)},` : "";
  return `// Auto-generated by \`dorm makemigrations\`. Edit freely — it's plain code.
export default {
  dependencies: ${JSON.stringify(dependencies)},${replacesLine}
  operations: (ops) => [
${opsCode}
  ],
};
`;
}

/** Write a new migration file and return its path + name. */
export function writeMigration(
  dir: string,
  operations: Operation[],
  opts: { name?: string } = {},
): { path: string; name: string } {
  mkdirSync(dir, { recursive: true });
  const existing = listMigrationFiles(dir);
  const { name } = nextMigrationName(dir, opts.name);
  const dependencies = existing.length > 0 ? [existing[existing.length - 1]!.name] : [];
  const path = join(dir, `${name}.ts`);
  writeFileSync(path, renderMigration(operations, dependencies));
  return { path, name };
}

/**
 * Write a squashed migration (design 10.1, `squashmigrations`): one numbered
 * 0001 file with `replaces` listing the whole history it stands in for. The
 * replaced files stay on disk during the transition and may be deleted once
 * every database has either fully applied them or starts fresh.
 */
export function writeSquashedMigration(
  dir: string,
  operations: Operation[],
  replaces: string[],
): { path: string; name: string } {
  mkdirSync(dir, { recursive: true });
  const last = replaces[replaces.length - 1]!;
  const name = `0001_squashed_${last}`;
  const path = join(dir, `${name}.ts`);
  writeFileSync(path, renderMigration(operations, [], replaces));
  return { path, name };
}
